### ISSUE TITLE
如何在Cocos Creator 中运行？

### ISSUE THREAD

**Issue by zdying** [cocos-creator/example-3d#8]
如何在Cocos Creator 中运行？demo1一致提示“正在导入资源，请稍后..."

![image](https://user-images.githubusercontent.com/3665170/60728514-18583480-9f73-11e9-92af-405a88e025a2.png)

demo2导入后无法运行。

![image](https://user-images.githubusercontent.com/3665170/60728593-4ccbf080-9f73-11e9-96a3-6de9a9cb7f82.png)

**Comment by YunHsiao** [comment]
这里是 creator 3D 的示例仓库，近期刚刚开始公测，欢迎申请试用：http://hdxu.cn/Tpuuu

**Comment by zdying** [comment]
好的，已申请。
